INSERT INTO Prices VALUES ('a',1);
INSERT INTO Prices VALUES ('b',2);
INSERT INTO Prices VALUES ('c',3);
INSERT INTO Prices VALUES ('d',4);
INSERT INTO Prices VALUES ('e',5);
INSERT INTO Prices VALUES ('f',6);
INSERT INTO Prices VALUES ('g',7);
INSERT INTO Prices VALUES ('h',8);
INSERT INTO Prices VALUES ('i',9);
INSERT INTO Prices VALUES ('j',10);
INSERT INTO Prices VALUES ('k',11);
INSERT INTO Prices VALUES ('l',12);
INSERT INTO Prices VALUES ('m',13);
INSERT INTO Prices VALUES ('n',14);
INSERT INTO Prices VALUES ('o',15);
INSERT INTO Prices VALUES ('p',16);
INSERT INTO Prices VALUES ('q',17);
INSERT INTO Prices VALUES ('r',18);
INSERT INTO Prices VALUES ('s',19);
INSERT INTO Prices VALUES ('t',1);
INSERT INTO Prices VALUES ('u',2);
INSERT INTO Prices VALUES ('v',3);
INSERT INTO Prices VALUES ('x',4);
INSERT INTO Prices VALUES ('y',5);




